project_id = "jbyssadthfjxwtszdqlq"

[functions.youtube-search]
verify_jwt = false

[functions.get-lyrics]
verify_jwt = false

[functions.get-audio-stream]
verify_jwt = false

[functions.audius-search]
verify_jwt = false
